AuthorBooksFluentApp/Models/Author.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using NHibernate.Criterion;

namespace AuthorBooksFluentApp.Models
{
    public class Author
    {
        public virtual Guid Id { get; set; }
        public virtual string UserName { get; set; }

        public virtual string Password { get; set; }
        public virtual string Name { get; set; }

        public virtual string Email { get; set; }

        public virtual int Age { get; set; }

        public virtual AuthorDetail AuthorDetail { get; set; } = new AuthorDetail();

        public virtual IList<Book> Book { get; set; } = new List<Book>();
    }
}

AuthorBooksFluentApp/Controllers/AuthorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Web.Security;
using AuthorBooksFluentApp.Data;
using AuthorBooksFluentApp.Models;
using AuthorBooksFluentApp.ViewModels;
using NHibernate.Linq;

namespace AuthorBooksFluentApp.Controllers
{
    public class AuthorController : Controller
    {
        // GET: Author
        public ActionResult Index()
        {
            if (Session["LoggedInAuthorId"] != null)
            {
                using (var session = NHibernateHelper.CreateSession())
                {
                    Guid loggedInAuthorId = (Guid)Session["LoggedInAuthorId"]; 

                    var author = session.Get<Author>(loggedInAuthorId);

                    return View(author);
                }
            }

            return RedirectToAction("Login");
        }


        [AllowAnonymous]
        public ActionResult Login()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginVM loginVM)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var txt = session.BeginTransaction())
                {
                    var user = session.Query<Author>().SingleOrDefault(u => u.UserName == loginVM.UserName);
                    if (user != null)
                    {
                        if (BCrypt.Net.BCrypt.Verify(loginVM.Password, user.Password))
                        {
                            FormsAuthentication.SetAuthCookie(loginVM.UserName, true);

                            Session["LoggedInAuthorId"] = user.Id;  
                            return RedirectToAction("Index");
                        }
                    }

                    ModelState.AddModelError("", "UserName/Password doesn't match");
                    return View();
                }
            }
        }


       
        [AllowAnonymous]
        public ActionResult Create()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpPost]

        public ActionResult Create(Author author)
        {
        
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    author.AuthorDetail.Author =author;
                    author.Password = BCrypt.Net.BCrypt.HashPassword(author.Password);
                    session.Save(author);
                    transaction.Commit();
                    return RedirectToAction("Index");
                }
            }


        }

        public ActionResult Edit(Guid id)  
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var author = session.Get<Author>(id); 
                return View(author);
            }
        }

        [HttpPost]
        public ActionResult Edit(Author author)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var existingAuthor = session.Get<Author>(author.Id);
                    existingAuthor.Name = author.Name;
                    existingAuthor.Email = author.Email;
                    existingAuthor.Age = author.Age;
                    existingAuthor.AuthorDetail.City = author.AuthorDetail.City;
                    existingAuthor.AuthorDetail.Street = author.AuthorDetail.Street;
                    existingAuthor.AuthorDetail.State = author.AuthorDetail.State;
                    existingAuthor.AuthorDetail.Country = author.AuthorDetail.Country;
                    author.AuthorDetail.Author = author;
                    session.Update(existingAuthor);
                    transaction.Commit();
                    return RedirectToAction("Index");
                }
            }
        }

        public ActionResult Delete(Guid id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var author = session.Query<Author>().FirstOrDefault(u => u.Id == id);
                return View(author);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteAuthor(Guid id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var author = session.Query<Author>().FirstOrDefault(u => u.Id == id);

                    author.AuthorDetail.City = "";
                    author.AuthorDetail.Street = "";
                    author.AuthorDetail.State = "";
                    author.AuthorDetail.Country = "";
                    session.Update(author);
                    transaction.Commit();
                    return RedirectToAction("Index");
                }
            }
        }

        [AllowAnonymous]
        public ActionResult BookList()
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                
                var books = session.Query<Book>().Fetch(b => b.Author).ToList();
                return View(books);
            }
        }

        [AllowAnonymous]
        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();
            return RedirectToAction("Login");
        }


    }
}

AuthorBooksFluentApp/Controllers/BookController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using AuthorBooksFluentApp.Data;
using AuthorBooksFluentApp.Models;

namespace AuthorBooksFluentApp.Controllers
{
    public class BookController : Controller
    {
        // GET: Book
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult BookDetails(Guid authId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var books = session.Query<Book>().Where(o => o.Author.Id == authId).ToList();
                Session["AuthId"] = authId; 

                return View(books);
            }
        }

        public ActionResult Create()
        {
            if (Session["AuthId"] != null)
            {
                Guid authId = (Guid)Session["AuthId"];
                ViewBag.AuthId = authId;
            }

            return View();
        }

        [HttpPost]
        public ActionResult Create(Book book, Guid authId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var author = session.Get<Author>(authId);
                    book.Author = author;

                    session.Save(book);
                    transaction.Commit();

                    return RedirectToAction("BookDetails", new { authId = author.Id });
                }
            }
        }

        public ActionResult Edit(int id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var book = session.Get<Book>(id);
                if (Session["AuthId"] != null)
                {
                    Guid authId = (Guid)Session["AuthId"];
                    ViewBag.AuthId = authId;
                }
                return View(book);
            }
        }

        [HttpPost]
        public ActionResult Edit(Book book, Guid authId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var existingBook = session.Get<Book>(book.Id);

                    existingBook.Name = book.Name;
                    existingBook.Description = book.Description;
                    existingBook.Genre = book.Genre;
                    existingBook.Author = session.Get<Author>(authId);

                    session.Update(existingBook);
                    transaction.Commit();

                    return RedirectToAction("BookDetails", new { authId = authId });
                }
            }
        }

        public ActionResult Delete(int id)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                var book = session.Get<Book>(id);
                Guid authId = (Guid)Session["AuthId"];
                ViewBag.AuthId = authId;
                return View(book);
            }
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id, Guid authId)
        {
            using (var session = NHibernateHelper.CreateSession())
            {
                using (var transaction = session.BeginTransaction())
                {
                    var book = session.Get<Book>(id);
                    session.Delete(book);
                    transaction.Commit();

                    return RedirectToAction("BookDetails", new { authId = authId });
                }
            }
        }
    }
}

AuthorBooksFluentApp/Views/Author/BookList.cshtml
@model IEnumerable<AuthorBooksFluentApp.Models.Book>

<h2 class="font-bold text-xl">Book List</h2>

<table class="table table-striped mb-80">
    <thead>
        <tr>
            <th>Book Name</th>
            <th>Genre</th>
            <th>Description</th>
            <th>Author</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Name</td>
                <td>@book.Genre</td>
                <td>@book.Description</td>
                <td>@book.Author.Name</td>
            </tr>
        }
    </tbody>
</table>

AuthorBooksFluentApp/Views/Author/Create.cshtml
@model AuthorBooksFluentApp.Models.Author


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm()) 
    {
        @Html.AntiForgeryToken()
        
<div class="form-horizontal shadow-2xl rounded-lg p-5">
    <h1 class="text-xl font-bold">Register</h1>

    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>
    @*<div class="form-group">
            <div class="col-md-10">
                @Html.EditorFor(model => model.AuthorDetail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AuthorDetail, "", new { @class = "text-danger" })
            </div>
        </div>*@

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default bg-green-600 text-white mt-2 hover:bg-green-700" />
        </div>
    </div>

    <div>
        Already a User ? @Html.ActionLink("Login", "Index" , new { @class="font-bold" })
    </div>
</div>
    }

</body>
</html>

AuthorBooksFluentApp/Views/Author/Delete.cshtml
@model AuthorBooksFluentApp.Models.Author


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        
            <dt class="mt-3">
                @Html.DisplayNameFor(model => model.AuthorDetail)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.AuthorDetail)
            </dd>

        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default bg-red-600 text-white mt-2 hover:bg-green-700" />
                <div>
                    @Html.ActionLink("Back to List", "Index")
                </div>
      
            </div>
        }
    </div>
</body>
</html>

AuthorBooksFluentApp/Views/Author/Edit.cshtml
@model AuthorBooksFluentApp.Models.Author



<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    
    
    @using (Html.BeginForm())   
    {
        @Html.AntiForgeryToken()
        
<div class="form-horizontal">
    <h4>Author</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
       
        <div class="col-md-10">
            @Html.EditorFor(model => model.AuthorDetail, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.AuthorDetail, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default bg-green-600 text-white mt-2 hover:bg-green-700"  />
        </div>
    </div>
</div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

AuthorBooksFluentApp/Views/Author/Index.cshtml
@model AuthorBooksFluentApp.Models.Author

<div class="container mx-auto p-6 mt-4 bg-white rounded shadow-lg">
    <h2 class="text-2xl font-bold mb-4">Author Details</h2>

    <p><strong>Name:</strong> <span class="text-gray-700">@Model.Name</span></p>
    <p><strong>Username:</strong> <span class="text-gray-700">@Model.UserName</span></p>
    <p><strong>Email:</strong> <span class="text-gray-700">@Model.Email</span></p>
    <p><strong>Age:</strong> <span class="text-gray-700">@Model.Age</span></p>

    <div class="mt-4">
        <h2><strong>Address Details : </strong></h2>
        <br />
        <p><strong>Street:</strong> <span class="text-gray-700">@Model.AuthorDetail.Street</span></p>
        <p><strong>City:</strong> <span class="text-gray-700">@Model.AuthorDetail.City</span></p>
        <p><strong>State:</strong> <span class="text-gray-700">@Model.AuthorDetail.State</span></p>
        <p><strong>Country:</strong> <span class="text-gray-700">@Model.AuthorDetail.Country</span></p>
    </div>

    <div class="mt-6 space-x-4">
        @Html.ActionLink("Edit Author Details", "Edit", new { id = Model.Id }, new { @class = "text-blue-600 hover:text-blue-800 font-semibold" })
        @Html.Raw("|")
        @Html.ActionLink("Delete Author Details", "Delete", new { id = Model.Id }, new { @class = "text-red-600 hover:text-red-800 font-semibold" })
        @Html.Raw("|")
        @Html.ActionLink("Book Details", "BookDetails", "Book", new { authId = Model.Id }, new { @class = "text-green-600 hover:text-green-800 font-semibold" })
    </div>
</div>

AuthorBooksFluentApp/Views/Author/Login.cshtml
@model AuthorBooksFluentApp.ViewModels.LoginVM

@{
    ViewBag.Title = "Login";
}

<div class="p-5 shadow-2xl  rounded-lg">
    <h1 class="text-2xl font-bold"> Login </h1>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">


            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control", type = "password" } })

                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Login" class="btn btn-default bg-green-600 text-white mt-2 hover:bg-green-700" />
                </div>
                Not A User ? @Html.ActionLink("Register", "Create", "Author" , new { @class = "font-bold" })
            </div>
        </div>
    }



</div>

AuthorBooksFluentApp/Views/Author/Register.cshtml
@model AuthorBooksFluentApp.Models.Author

@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Author</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>